name: Publish Maven package to GitHub Packages
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5
      - name: Publish package
        run: gradle publish
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
